### ISSUE TITLE
Error during execution

### ISSUE THREAD

**Issue by olyarybalko** [tdunning/k-means-auto-encoder#1]
[1] 10
[1] 100
[1] 200
[1] 500
[1] 1000
[1] 2000
Error in png(file = "images/time-series-errors.png", width = 400, height = 400) : 
  impossible de démarrer le périphérique png()
In addition: Warning messages:
1: In png(file = "images/time-series-errors.png", width = 400, height = 400) :
  impossible d'ouvrir le fichier 'images/time-series-errors.png' pour écriture
2: In png(file = "images/time-series-errors.png", width = 400, height = 400) :
  opening device failed

**Comment by tdunning** [comment]
This appears to be a problem with you r installation. That is odd because I
thought that png() is part of base r.

Is is also possible that this is locale related or due to permission
problems.

Can you set language to en_US to see if that is the problem?  And check the
directory permission?

Also what command did you run? What os? What Java? What r version?

On May 10, 2017 1:10 PM, "olyarybalko" <notifications@github.com> wrote:

[1] 10
[1] 100
[1] 200
[1] 500
[1] 1000
[1] 2000
Error in png(file = "images/time-series-errors.png", width = 400, height =
400) :
impossible de démarrer le périphérique png()
In addition: Warning messages:
1: In png(file = "images/time-series-errors.png", width = 400, height =
400) :
impossible d'ouvrir le fichier 'images/time-series-errors.png' pour écriture
2: In png(file = "images/time-series-errors.png", width = 400, height =
400) :
opening device failed

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tdunning/k-means-auto-encoder/issues/1>, or mute the
thread

**Comment by tdunning** [comment]
Closing this.
